### ISSUE TITLE
Java generator: Reserved getter methods should be private

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catbuffer-generators#100]
/**
     * Gets reserved padding to align Signature on 8-byte boundary.
     *
     * @return Reserved padding to align Signature on 8-byte boundary.
     */
    public int getVerifiableEntityHeader_Reserved1() {
        return this.verifiableEntityHeader_Reserved1;
    }

**Comment by fboucquez** [comment]
@Wayonb 

The alternative would be to remove the reserved fields altogether and serialize 0 when required (similar to size attributes that are not stored in the builder). Maybe having an extra attribute kind or keep it simple with an if condition. What do you think?

**Comment by Wayonb** [comment]
@fboucquez That's fine.  From a readability keeping the fields around is good but you can always add some comments.
