### ISSUE TITLE
Java Generator: AggregateTransactionBodyBuilder is a static file

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catbuffer-generators#101]
AggregateTransactionBodyBuilder is a static file and should be generated as any other builder class.  If the catbuffer schema file is updated then this file will also need to change.

**Comment by fboucquez** [comment]
This issue should be fixed before branching the java generator into a new language. If not, a new language may replicate the issue as current mako templates don't support AggregateTransactionBodyBuilder

**Comment by fboucquez** [comment]
Fixed

**Comment by gimer** [comment]
@fboucquez if this has been fixed, I don't think it was merged into main

**Comment by fboucquez** [comment]
Uff, you are right, I've fixed it on Typescript but not on Java. Java solution would be similar to Typescript.
