### ISSUE TITLE
update cpp_builder to support aggregate transaction builder

### ISSUE THREAD

**Issue by Jaguar0625** [nemtech/catbuffer-generators#26]
also remove line from .travis.yml
```yaml
- python3 main.py --schema ./schemas/aggregate/aggregate.cats # temporary until generate_all.sh/cpp_builder are updated
```

**Comment by fboucquez** [comment]
Cpp generator is behind the counterparts. Features to consider:

- Use mako templates
- Compile the around [here](https://github.com/nemtech/catbuffer-generators/blob/main/scripts/generate_cpp.sh#L19) for validation
- Deploy a Conan package/library (alpha and prod version).
