### ISSUE TITLE
Build the typescript generated code in the project

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catbuffer-generators#63]
Build the typescript generated code in the project (not in the sdk) so you can test that the generated code compiles at least. 

In Java, I generate/copy all the necessary Gradle files to do the  build Java in this project

https://github.com/NEMStudios/catbuffer-generators/blob/f2_changes_jar_packages/scripts/generate_and_build_java.sh#L41

You can do the same by using npm configuration. This would save you time as this tool will check that the code is correct (when generating in cmd and Travis). I'm guessing you need to copy the code over the SDK project to validate it.

_Originally posted by @fboucquez in https://github.com/nemtech/catbuffer-generators/pull/61#issuecomment-568480085_

**Comment by rg911** [comment]
second to this point, build into Jar / npm package would be idea as it clears a lot hassle when applying the new generated to code in SDK. 

The concern here is how to automate the test. It should be better to add testing code which ideally generated by the generator, and integrated in to the build process (travis e.g. ) before the deploy

**Comment by fboucquez** [comment]
Adding unit test to the generated code is definitely interesting. Not super simple though. Should we keep this issue to add them to both java and ts?

**Comment by rg911** [comment]
Perhaps we can add unit tests projects with lint checking enabled? But yes, this will definitely be a separate issue I believe

**Comment by fboucquez** [comment]
Typescript is deploying an npm package. Closing this issue.
